# Generated by Django 4.1 on 2023-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('poster', models.ImageField(max_length=200, null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('eventTime', models.TimeField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
