# Generated by Django 4.1 on 2023-02-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnp', '0003_alter_event_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('resourceNeed', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
    ]
