# Generated by Django 4.1 on 2023-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnp', '0004_requestresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestresource',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
